package server

// Transaction Binding and Security
//
// A CMP transaction groups all messages in a single enrollment exchange (e.g., IR→IP→CertConf→PKIConf).
// The transactionID field in the PKIHeader identifies the transaction — it's a 128-bit random value
// generated by the client and echoed by the server in responses (RFC 9810 §5.1.1).
//
// Since the transactionID is client-controlled, the server must prevent one client from
// hijacking another client's transaction by sending follow-up messages (CertConf, PollReq)
// with a guessed or observed transactionID.
//
// The solution is to use a composite key: hash(credentialID + transactionID). This ensures
// that two clients with different credentials have completely separate key spaces, even if
// they use the same transactionID. The credentialID is derived from what the server verified:
//   - MAC protection: hash of SenderKID (references the shared secret)
//   - Signature protection: hash of the signer certificate
//
// This is secure because the credentialID is not client-controlled — it's derived from
// the cryptographic proof the client provided. An attacker would need the victim's
// shared secret or private key to produce a matching composite key.

import (
	"crypto/sha256"
	"crypto/x509"
	"sync"
	"time"

	"github.com/tsaarni/go-pkicmp/pkicmp"
)

// transactionKey is a composite key derived from credentialID and transactionID.
// It ensures different clients cannot access each other's transactions.
type transactionKey [sha256.Size]byte

func makeKey(credentialID, transactionID []byte) transactionKey {
	h := sha256.New()
	h.Write(credentialID)
	h.Write(transactionID)
	var key transactionKey
	copy(key[:], h.Sum(nil))
	return key
}

// txnState represents the current phase of a transaction.
type txnState int

const (
	stateActive  txnState = iota // Transaction started, awaiting CA response
	statePending                 // CA returned "waiting", awaiting poll
	stateIssued                  // Certificate issued, awaiting certConf
)

// transactionEntry holds all state for a single transaction.
// A transaction is in exactly one state at a time.
type transactionEntry struct {
	state     txnState
	createdAt time.Time

	// Set when state == statePending
	reqType RequestType
	pollRef string

	// Set when state == stateIssued
	cert             *x509.Certificate
	senderNonce      []byte
	clientSenderNonce []byte          // client's original senderNonce from the cert request
	macOptions       *pkicmp.MACOptions // PBM parameters from the client's request
}

// transactionTracker manages transaction state for the CMP server.
// All methods require credentialID and transactionID, ensuring the composite key
// is always computed correctly. This prevents misuse by making it impossible to
// pass a raw key.
type transactionTracker struct {
	transactions sync.Map // transactionKey → transactionEntry
}

func newTransactionTracker() *transactionTracker {
	return &transactionTracker{}
}

func (t *transactionTracker) start(credentialID, transactionID []byte) {
	t.transactions.Store(makeKey(credentialID, transactionID), transactionEntry{
		state:     stateActive,
		createdAt: time.Now(),
	})
}

func (t *transactionTracker) exists(credentialID, transactionID []byte) bool {
	_, ok := t.transactions.Load(makeKey(credentialID, transactionID))
	return ok
}

func (t *transactionTracker) setPending(credentialID, transactionID []byte, reqType RequestType, pollRef string) {
	t.transactions.Store(makeKey(credentialID, transactionID), transactionEntry{
		state:     statePending,
		createdAt: time.Now(),
		reqType:   reqType,
		pollRef:   pollRef,
	})
}

func (t *transactionTracker) getPending(credentialID, transactionID []byte) (*transactionEntry, bool) {
	v, ok := t.transactions.Load(makeKey(credentialID, transactionID))
	if !ok {
		return nil, false
	}
	entry := v.(transactionEntry)
	if entry.state != statePending {
		return nil, false
	}
	return &entry, true
}

func (t *transactionTracker) setIssued(credentialID, transactionID []byte, cert *x509.Certificate, senderNonce, clientSenderNonce []byte, macOptions *pkicmp.MACOptions) {
	t.transactions.Store(makeKey(credentialID, transactionID), transactionEntry{
		state:             stateIssued,
		createdAt:         time.Now(),
		cert:              cert,
		senderNonce:       senderNonce,
		clientSenderNonce: clientSenderNonce,
		macOptions:        macOptions,
	})
}

func (t *transactionTracker) getIssued(credentialID, transactionID []byte) (*transactionEntry, bool) {
	v, ok := t.transactions.Load(makeKey(credentialID, transactionID))
	if !ok {
		return nil, false
	}
	entry := v.(transactionEntry)
	if entry.state != stateIssued {
		return nil, false
	}
	return &entry, true
}

func (t *transactionTracker) delete(credentialID, transactionID []byte) {
	t.transactions.Delete(makeKey(credentialID, transactionID))
}

// cleanupExpired removes entries older than maxAge.
func (t *transactionTracker) cleanupExpired(maxAge time.Duration) {
	if maxAge <= 0 {
		return
	}
	cutoff := time.Now().Add(-maxAge)
	t.transactions.Range(func(key, value any) bool {
		if entry := value.(transactionEntry); entry.createdAt.Before(cutoff) {
			t.transactions.Delete(key)
		}
		return true
	})
}
