package server

// Transaction Binding and Security
//
// A CMP transaction groups all messages in a single enrollment exchange (e.g., IR→IP→CertConf→PKIConf).
// The transactionID field in the PKIHeader identifies the transaction — it's a 128-bit random value
// generated by the client and echoed by the server in responses (RFC 9810 §5.1.1).
//
// Since the transactionID is client-controlled, the server must prevent one client from
// hijacking another client's transaction by sending follow-up messages (CertConf, PollReq)
// with a guessed or observed transactionID.
//
// The solution is to use a composite key: hash(credentialID + transactionID). This ensures
// that two clients with different credentials have completely separate key spaces, even if
// they use the same transactionID. The credentialID is derived from what the server verified:
//   - MAC protection: hash of SenderKID (references the shared secret)
//   - Signature protection: hash of the signer certificate
//
// This is secure because the credentialID is not client-controlled — it's derived from
// the cryptographic proof the client provided. An attacker would need the victim's
// shared secret or private key to produce a matching composite key.

import (
	"crypto/sha256"
	"crypto/x509"
	"encoding/binary"
	"errors"
	"sync"
	"sync/atomic"
	"time"

	"github.com/tsaarni/go-pkicmp/pkicmp"
)

// transactionKey is a composite key derived from credentialID and transactionID.
// It ensures different clients cannot access each other's transactions.
type transactionKey [sha256.Size]byte

// credentialKey is a hash of the credentialID used for per-credential counting.
type credentialKey [sha256.Size]byte

// makeKey computes a composite key with length-prefixed components to prevent
// ambiguity from concatenation of variable-length inputs.
func makeKey(credentialID, transactionID []byte) transactionKey {
	h := sha256.New()
	var buf [4]byte
	binary.BigEndian.PutUint32(buf[:], uint32(len(credentialID))) // #nosec G115 -- length prefix for domain separation; CMP IDs are bounded by message size
	h.Write(buf[:])
	h.Write(credentialID)
	binary.BigEndian.PutUint32(buf[:], uint32(len(transactionID))) // #nosec G115 -- length prefix for domain separation; CMP IDs are bounded by message size
	h.Write(buf[:])
	h.Write(transactionID)
	var key transactionKey
	copy(key[:], h.Sum(nil))
	return key
}

// makeCredentialKey computes a hash of the credentialID for per-credential counting.
func makeCredentialKey(credentialID []byte) credentialKey {
	return credentialKey(sha256.Sum256(credentialID))
}

// txnState represents the current phase of a transaction.
type txnState int

const (
	stateActive    txnState = iota // Transaction started, awaiting CA response
	statePending                   // CA returned "waiting", awaiting poll
	stateIssued                    // Certificate issued, awaiting certConf
	stateCompleted                 // Transaction done (implicit confirm granted); kept until cleanupExpired to block transactionID reuse
)

// transactionEntry holds all state for a single transaction.
// A transaction is in exactly one state at a time.
type transactionEntry struct {
	state         txnState
	lastActivity  time.Time
	credentialKey credentialKey

	// Set when state == statePending
	reqType      RequestType
	pollRef      string
	senderNonce  []byte        // server's senderNonce from the waiting response (for recipNonce verification)
	lastPollTime time.Time     // last time a poll was received (zero for initial pending)
	checkAfter   time.Duration // minimum interval between polls

	// Set when state == stateIssued
	cert              *x509.Certificate
	issueRef          any                        // opaque CA reference for CertificateConfirmer
	issuedSenderNonce []byte                     // server's senderNonce from the issued response
	clientSenderNonce []byte                     // client's original senderNonce from the cert request
	protectionParams  pkicmp.MACCredentialOption // decoded protection parameters for echo-back
}

// transactionTracker manages transaction state for the CMP server.
// All methods require credentialID and transactionID, ensuring the composite key
// is always computed correctly. This prevents misuse by making it impossible to
// pass a raw key.
type transactionTracker struct {
	transactions sync.Map // transactionKey → *transactionEntry

	count                        atomic.Int64
	maxTransactions              int
	credentialCounts             sync.Map // credentialKey → *atomic.Int64
	maxTransactionsPerCredential int
}

func newTransactionTracker(maxTxn, maxPerCred int) *transactionTracker {
	return &transactionTracker{
		maxTransactions:              maxTxn,
		maxTransactionsPerCredential: maxPerCred,
	}
}

// startIfAbsent atomically creates a new transaction if one does not already exist.
// Returns (true, nil) if the transaction already existed, (false, nil) on success,
// or (false, err) if limits are exceeded.
func (t *transactionTracker) startIfAbsent(credentialID, transactionID []byte) (alreadyExists bool, err error) {
	key := makeKey(credentialID, transactionID)
	ck := makeCredentialKey(credentialID)

	// Reserve capacity before storing to prevent transient overshoot.
	newCount := t.count.Add(1)
	if int(newCount) > t.maxTransactions {
		t.count.Add(-1)
		return false, errors.New("maximum transaction limit reached")
	}

	credCount := t.getOrCreateCredCount(ck)
	newCredCount := credCount.Add(1)
	if int(newCredCount) > t.maxTransactionsPerCredential {
		credCount.Add(-1)
		t.count.Add(-1)
		return false, errors.New("per-credential transaction limit reached")
	}

	entry := &transactionEntry{
		state:         stateActive,
		lastActivity:  time.Now(),
		credentialKey: ck,
	}

	// Atomically check existence and store.
	_, loaded := t.transactions.LoadOrStore(key, entry)
	if loaded {
		// Already existed — release reserved capacity.
		credCount.Add(-1)
		t.count.Add(-1)
		return true, nil
	}

	return false, nil
}

// getOrCreateCredCount returns the atomic counter for a credential key.
func (t *transactionTracker) getOrCreateCredCount(ck credentialKey) *atomic.Int64 {
	val, _ := t.credentialCounts.LoadOrStore(ck, &atomic.Int64{})
	return val.(*atomic.Int64)
}

func (t *transactionTracker) setPending(credentialID, transactionID []byte, reqType RequestType, pollRef string, senderNonce []byte, checkAfter time.Duration, lastPollTime time.Time) bool {
	key := makeKey(credentialID, transactionID)
	ck := makeCredentialKey(credentialID)

	// Load current entry and verify expected state.
	old, ok := t.transactions.Load(key)
	if !ok {
		return false
	}
	oldEntry := old.(*transactionEntry)
	if oldEntry.state != stateActive && oldEntry.state != statePending {
		return false
	}

	newEntry := &transactionEntry{
		state:         statePending,
		lastActivity:  time.Now(),
		credentialKey: ck,
		reqType:       reqType,
		pollRef:       pollRef,
		senderNonce:   senderNonce,
		lastPollTime:  lastPollTime,
		checkAfter:    checkAfter,
	}
	return t.transactions.CompareAndSwap(key, old, newEntry)
}

func (t *transactionTracker) getPending(credentialID, transactionID []byte) (*transactionEntry, bool) {
	v, ok := t.transactions.Load(makeKey(credentialID, transactionID))
	if !ok {
		return nil, false
	}
	entry := v.(*transactionEntry)
	if entry.state != statePending {
		return nil, false
	}
	return entry, true
}

func (t *transactionTracker) setIssued(credentialID, transactionID []byte, cert *x509.Certificate, issueRef any, senderNonce, clientSenderNonce []byte, protectionParams pkicmp.MACCredentialOption) bool {
	key := makeKey(credentialID, transactionID)
	ck := makeCredentialKey(credentialID)

	// Load current entry and verify expected state.
	old, ok := t.transactions.Load(key)
	if !ok {
		return false
	}
	oldEntry := old.(*transactionEntry)
	if oldEntry.state != stateActive && oldEntry.state != statePending {
		return false
	}

	newEntry := &transactionEntry{
		state:             stateIssued,
		lastActivity:      time.Now(),
		credentialKey:     ck,
		cert:              cert,
		issueRef:          issueRef,
		issuedSenderNonce: senderNonce,
		clientSenderNonce: clientSenderNonce,
		protectionParams:  protectionParams,
	}
	return t.transactions.CompareAndSwap(key, old, newEntry)
}

func (t *transactionTracker) getIssued(credentialID, transactionID []byte) (*transactionEntry, bool) {
	v, ok := t.transactions.Load(makeKey(credentialID, transactionID))
	if !ok {
		return nil, false
	}
	entry := v.(*transactionEntry)
	if entry.state != stateIssued {
		return nil, false
	}
	return entry, true
}

// setCompleted marks a transaction as done without deleting it, keeping the
// transactionID locked until cleanupExpired removes the entry. This prevents
// a client from reusing the same transactionID within the same confirmWaitTime
// window (RFC 9483 §3.5).
func (t *transactionTracker) setCompleted(credentialID, transactionID []byte) {
	key := makeKey(credentialID, transactionID)
	if v, ok := t.transactions.Load(key); ok {
		entry := v.(*transactionEntry)
		entry.state = stateCompleted
		entry.lastActivity = time.Now()
	}
}

func (t *transactionTracker) delete(credentialID, transactionID []byte) {
	key := makeKey(credentialID, transactionID)
	v, loaded := t.transactions.LoadAndDelete(key)
	if loaded {
		entry := v.(*transactionEntry)
		t.count.Add(-1)
		credCount := t.getOrCreateCredCount(entry.credentialKey)
		credCount.Add(-1)
	}
}

// expiredIssued holds details of an expired issued transaction for CA notification.
type expiredIssued struct {
	cert     *x509.Certificate
	issueRef any
}

// cleanupExpired removes entries older than maxAge and returns any expired
// issued transactions (certificates that were never confirmed).
func (t *transactionTracker) cleanupExpired(maxAge time.Duration) []expiredIssued {
	if maxAge <= 0 {
		return nil
	}
	var expired []expiredIssued
	cutoff := time.Now().Add(-maxAge)
	t.transactions.Range(func(key, value any) bool {
		entry := value.(*transactionEntry)
		if entry.lastActivity.Before(cutoff) {
			_, loaded := t.transactions.LoadAndDelete(key)
			if loaded {
				t.count.Add(-1)
				credCount := t.getOrCreateCredCount(entry.credentialKey)
				credCount.Add(-1)
				if entry.state == stateIssued && entry.cert != nil {
					expired = append(expired, expiredIssued{
						cert:     entry.cert,
						issueRef: entry.issueRef,
					})
				}
			}
		}
		return true
	})
	return expired
}
