package pkicmp_test

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/tsaarni/go-pkicmp/pkicmp"
)

func TestP10CRRoundTrip(t *testing.T) {
	// 1. Create a CSR
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	require.NoError(t, err)
	template := &x509.CertificateRequest{
		Subject: pkix.Name{
			CommonName: "Test User",
		},
	}
	csrDER, err := x509.CreateCertificateRequest(rand.Reader, template, key)
	require.NoError(t, err)
	csr, err := x509.ParseCertificateRequest(csrDER)
	require.NoError(t, err)

	// 2. Build PKIMessage
	body, err := pkicmp.NewP10CRBody(csr)
	require.NoError(t, err)

	msg := &pkicmp.PKIMessage{
		Header: pkicmp.PKIHeader{
			Sender:        pkicmp.NewDirectoryName(pkix.RDNSequence{{{Type: []int{2, 5, 4, 3}, Value: "Sender"}}}),
			Recipient:     pkicmp.NewDirectoryName(pkix.RDNSequence{{{Type: []int{2, 5, 4, 3}, Value: "Recipient"}}}),
			TransactionID: []byte("trans-123"),
			SenderNonce:   []byte("nonce-123"),
		},
		Body: body,
	}

	// 3. Marshal
	der, err := msg.MarshalBinary()
	require.NoError(t, err)

	// 4. Parse
	parsed, err := pkicmp.ParsePKIMessage(der)
	require.NoError(t, err)

	// 5. Verify fields
	assert.Equal(t, pkicmp.PVNO2, parsed.Header.PVNO) // Should default to v2 for p10cr
	assert.Equal(t, []byte("trans-123"), parsed.Header.TransactionID)
	assert.Equal(t, pkicmp.BodyTypeP10CR, parsed.Body.Type)

	parsedCSR, err := parsed.Body.P10CR()
	require.NoError(t, err)
	assert.Equal(t, csr.Subject.String(), parsedCSR.Subject.String())
	assert.Equal(t, csr.Raw, parsedCSR.Raw)
}

func TestImplicitPVNO3Upgrades(t *testing.T) {
	t.Run("CertConfWithHashAlg", func(t *testing.T) {
		// hashAlg in certConf triggers PVNO3
		conf := pkicmp.NewCertConfirmContent(
			pkicmp.NewCertStatusWithHashAlg([]byte("hash"), 123, &pkicmp.AlgorithmIdentifier{Algorithm: pkicmp.OIDSHA256}),
		)
		body, err := pkicmp.NewCertConfBody(conf)
		require.NoError(t, err)

		msg := &pkicmp.PKIMessage{
			Header: pkicmp.PKIHeader{
				Sender:    pkicmp.NewDirectoryName(pkix.RDNSequence{}),
				Recipient: pkicmp.NewDirectoryName(pkix.RDNSequence{}),
			},
			Body: body,
		}

		der, err := msg.MarshalBinary()
		require.NoError(t, err)

		parsed, err := pkicmp.ParsePKIMessage(der)
		require.NoError(t, err)

		assert.Equal(t, pkicmp.PVNO3, parsed.Header.PVNO)

		gotConf, err := parsed.Body.CertConf()
		require.NoError(t, err)
		assert.Len(t, *gotConf, 1)
		assert.Equal(t, pkicmp.OIDSHA256, (*gotConf)[0].HashAlg.Algorithm)
	})

	t.Run("POPOPrivKeyEncryptedKey", func(t *testing.T) {
		req := pkicmp.CertReqMessages{
			{
				CertReq: pkicmp.CertRequest{CertReqID: 1},
				Popo: &pkicmp.ProofOfPossession{
					KeyEncipherment: &pkicmp.POPOPrivKey{
						EncryptedKey: &pkicmp.EnvelopedData{Raw: []byte{0x30, 0x00}},
					},
				},
			},
		}

		body, err := pkicmp.NewIRBody(&req)
		require.NoError(t, err)

		msg := &pkicmp.PKIMessage{
			Header: pkicmp.PKIHeader{TransactionID: []byte("trans")},
			Body:   body,
		}

		der, err := msg.MarshalBinary()
		require.NoError(t, err)

		parsed, err := pkicmp.ParsePKIMessage(der)
		require.NoError(t, err)

		assert.Equal(t, pkicmp.PVNO3, parsed.Header.PVNO)
	})
}

func TestRoundTripOpenSSLGeneratedMessages(t *testing.T) {
	// These tests verify that pkicmp can parse raw ASN.1 messages generated by OpenSSL 3.0.
	// The golden .der files can be recreated using the script in testdata/generate.sh.

	t.Run("IR", func(t *testing.T) {
		der, err := os.ReadFile("testdata/ir_golden.der")
		require.NoError(t, err)

		msg, err := pkicmp.ParsePKIMessage(der)
		require.NoError(t, err)

		assert.Equal(t, pkicmp.PVNO2, msg.Header.PVNO)
		assert.Equal(t, pkicmp.BodyTypeIR, msg.Body.Type)

		marshaled, err := msg.MarshalBinary()
		require.NoError(t, err)
		assert.Equal(t, der, marshaled)
	})

	t.Run("CR", func(t *testing.T) {
		der, err := os.ReadFile("testdata/cr_golden.der")
		require.NoError(t, err)

		msg, err := pkicmp.ParsePKIMessage(der)
		require.NoError(t, err)

		assert.Equal(t, pkicmp.PVNO2, msg.Header.PVNO)
		assert.Equal(t, pkicmp.BodyTypeCR, msg.Body.Type)

		marshaled, err := msg.MarshalBinary()
		require.NoError(t, err)
		assert.Equal(t, der, marshaled)
	})

	t.Run("KUR", func(t *testing.T) {
		der, err := os.ReadFile("testdata/kur_golden.der")
		require.NoError(t, err)

		msg, err := pkicmp.ParsePKIMessage(der)
		require.NoError(t, err)

		assert.Equal(t, pkicmp.PVNO2, msg.Header.PVNO)
		assert.Equal(t, pkicmp.BodyTypeKUR, msg.Body.Type)

		marshaled, err := msg.MarshalBinary()
		require.NoError(t, err)
		assert.Equal(t, der, marshaled)
	})

	t.Run("P10CR", func(t *testing.T) {
		der, err := os.ReadFile("testdata/p10cr_golden.der")
		require.NoError(t, err)

		msg, err := pkicmp.ParsePKIMessage(der)
		require.NoError(t, err)

		assert.Equal(t, pkicmp.PVNO2, msg.Header.PVNO)
		assert.Equal(t, pkicmp.BodyTypeP10CR, msg.Body.Type)

		marshaled, err := msg.MarshalBinary()
		require.NoError(t, err)
		assert.Equal(t, der, marshaled)
	})
}

func TestParseRejectsInvalidASN1Structure(t *testing.T) {
	// These tests verify that the parser correctly identifies and rejects malformed ASN.1 structures.

	t.Run("MismatchedHeaderTag", func(t *testing.T) {
		der, err := os.ReadFile("testdata/ir_golden.der")
		require.NoError(t, err)

		// Change the main PKIHeader sequence tag (index 4) from 0x30 to 0x31 (Set)
		tampered := make([]byte, len(der))
		copy(tampered, der)
		tampered[4] = 0x31

		_, err = pkicmp.ParsePKIMessage(tampered)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "invalid PKIHeader sequence")
	})

	t.Run("InvalidBodyTag", func(t *testing.T) {
		// Deliberately malformed PKIMessage where Body tag 0xa4 (KUR) is followed by empty content.
		badDer := []byte{
			0x30, 0x11, // PKIMessage
			0x30, 0x0b, 0x02, 0x01, 0x02, 0xa4, 0x02, 0x30, 0x00, 0xa4, 0x02, 0x30, 0x00, // PKIHeader
			0xa4, 0x00, // Body tag 0xa4 = KUR instead of PKIConf
		}

		_, err := pkicmp.ParsePKIMessage(badDer)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "invalid PKIMessage sequence")
	})
}
